-- verificar db link na origem enquanto clona:
SET LINES 400
COL DB_LINK FOR a40
COL USERNAME FOR A30
COL HOST FOR A50
SELECT DB_LINK, HOST, USERNAME, CREATED FROM DBA_DB_LINKS;

-- verificar historico de conexoes no destino:

set lines window
col db_name for a20
col USERNAME for a20
col LAST_LOGON_TIME for a40
SELECT DB_NAME, USERNAME, LAST_LOGON_TIME, LOGON_COUNT FROM DBA_DB_LINK_SOURCES;

-- No vídeo Gravação Tarde 01:09:13
-- REFRESHABLE PDB

-- Origem Carapebus1 (172.29.17.51)
-- conectado como SYSDBA
CREATE USER c##ref_admin IDENTIFIED BY "senha";

GRANT CREATE SESSION, RESOURCE, CREATE ANY TABLE, UNLIMITED TABLESPACE TO c##ref_admin CONTAINER=ALL;

GRANT CREATE PLUGGABLE DATABASE TO c##ref_admin CONTAINER=ALL;

GRANT SYSOPER TO c##ref_admin CONTAINER=ALL;

-- destino RAC Carapebus (172.29.17.151)
-- conectado como SYSDBA
CREATE USER c##ref_admin IDENTIFIED BY "senha";

GRANT CREATE SESSION, RESOURCE, CREATE ANY TABLE, UNLIMITED TABLESPACE TO c##ref_admin CONTAINER=ALL;

GRANT CREATE PLUGGABLE DATABASE TO c##ref_admin CONTAINER=ALL;

GRANT SYSOPER TO c##ref_admin CONTAINER=ALL;

--CREATE DATABASE LINK carapebus_old CONNECT TO c##ref_admin IDENTIFIED BY "senha" USING 'ORIGEM';

CREATE DATABASE LINK carapebus_old CONNECT TO c##ref_admin IDENTIFIED BY "senha" USING 
'(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=172.29.17.51)(PORT = 1521)) (CONNECT_DATA=(SERVER = DEDICATED)(SERVICE_NAME = emrep)))';

set timing on
--DROP PLUGGABLE DATABASE PDBOLM INCLUDING DATAFILES;

--DROP PLUGGABLE DATABASE CATALOGO INCLUDING DATAFILES;

--DROP PLUGGABLE DATABASE EMPDBREPOS INCLUDING DATAFILES;

CREATE PLUGGABLE DATABASE PDBOLM FROM pdbolm@carapebus_old REFRESH MODE EVERY 5 MINUTES;

ALTER PLUGGABLE DATABASE PDBOLM OPEN READ ONLY;

ALTER PLUGGABLE DATABASE PDBOLM CLOSE IMMEDIATE;

CREATE PLUGGABLE DATABASE CATALOGO FROM catalogo@carapebus_old REFRESH MODE EVERY 5 MINUTES;

ALTER PLUGGABLE DATABASE CATALOGO OPEN READ ONLY;

ALTER PLUGGABLE DATABASE CATALOGO CLOSE IMMEDIATE;

CREATE PLUGGABLE DATABASE EMPDBREPOS FROM empdbrepos@carapebus_old REFRESH MODE EVERY 5 MINUTES;

ALTER PLUGGABLE DATABASE EMPDBREPOS OPEN READ ONLY;

ALTER PLUGGABLE DATABASE EMPDBREPOS CLOSE IMMEDIATE;


-- Verificação do status e SCN da última sincronização
SET LINE WINDOW
COL PDB_NAME FOR A25
SELECT PDB_ID, PDB_NAME, REFRESH_MODE, STATUS, REFRESH_INTERVAL, LAST_REFRESH_SCN, SCN_TO_TIMESTAMP(LAST_REFRESH_SCN) AS LASTREFRESH FROM DBA_PDBS WHERE STATUS = 'REFRESHING';


-- Alterar o intervalo de sincronização
ALTER PLUGGABLE DATABASE PDBOLM REFRESH MODE EVERY 10 MINUTES;

ALTER PLUGGABLE DATABASE CATALOGO REFRESH MODE EVERY 10 MINUTES;

ALTER PLUGGABLE DATABASE EMPDBREPOS REFRESH MODE EVERY 10 MINUTES;

-- Alterar o mondo de sincrinização enter manual e automático
ALTER PLUGGABLE DATABASE PDBOLM REFRESH MODE MANUAL;

-- Abrir o PDB para leitura e escrita

ALTER PLUGGABLE DATABASE PDBOLM CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE PDBOLM REFRESH;

ALTER PLUGGABLE DATABASE PDBOLM REFRESH MODE NONE;

ALTER PLUGGABLE DATABASE PDBOLM OPEN;

-- Fazer o SWITCHOVER entre os PDBs origem e destino
-- Essa é uma feature disponível apenas para Engineered Systems (Extadata)
-- Para usar nos demais abientes, deve ser habilitado o parâmetro oculto _exadata_feature_on
alter system set "_exadata_feature_on"=true scope=spfile;

shutdown immediate

ALTER SESSION SET CONTAINER=cdb$root;

ALTER PLUGGABLE DATABASE REFRESH MODE EVERY 60 MINUTES FROM pdbolm@ref_dblink SWITCHOVER;

ALTER SESSION SET CONTAINER=cdb$root;



startup

ALTER PLUGGABLE DATABASE src_pdb OPEN;

ALTER SESSION SET CONTAINER = src_pdb;

-- SWITCHOVER

ALTER PLUGGABLE DATABASE REFRESH MODE EVERY 60 MINUTES FROM ref_pdb@ref_dblink SWITCHOVER;

show pdbs

ALTER PLUGGABLE DATABASE OPEN READ ONLY;

-- destino

ALTER SESSION SET CONTAINER=ref_pdb;

CREATE TABLE t2(n1 NUMBER);

INSERT INTO t2 VALUES(1);

COMMIT;

-- origem

ALTER SESSION SET CONTAINER = src_pdb;

SELECT * FROM T2;

SELECT last_refresh_scn FROM dba_pdbs WHERE pdb_name = 'SRC_PDB';

ALTER PLUGGABLE DATABASE src_pdb CLOSE IMMEDIATE;

ALTER PLUGGABLE DATABASE REFRESH;

ALTER PLUGGABLE DATABASE src_pdb OPEN READ ONLY;

SELECT last_refresh_scn FROM dba_pdbs WHERE pdb_name = 'SRC_PDB';

SELECT * FROM T2;
